apiVersion: apps/v1  # Указывает версию API, которую использует Kubernetes для манифестов развертывания.
kind: Deployment  # Определяет тип ресурса как Deployment. Deployment управляет ReplicaSets и обновлением подов.
metadata:
  name: fastapi-app  # Название Deployment, используемое для идентификации объекта в кластере.
spec:
  replicas: 1  # Указывает количество реплик контейнеров (поды). Здесь задано 1 - то есть будет запущена 1 копия приложения.
  selector:
    matchLabels:
      app: fastapi-app  # Это селектор для выбора подов с конкретными метками. В данном случае выбираются поды с меткой `app: fastapi-app`.
  template:  # Определяет шаблон для создания подов. Включает спецификацию контейнеров, их окружение и другие настройки.
    metadata:
      labels:
        app: fastapi-app  # Метки для созданных подов. Эти метки будут использоваться для их идентификации.
    spec:
      containers:
      - name: fastapi-app  # Название контейнера внутри пода.
        image: pet_app-app:latest  # Здесь указывается Docker image для запуска контейнера. Подробнее ниже.
        imagePullPolicy: Never # Это чтобы оно всегда искало image в локальной директории докера, а не на DockerHub
        ports:
        - containerPort: 8080  # Открытый порт внутри контейнера (для приложения FastAPI). Внешние сервисы будут взаимодействовать через этот порт.
        env:  # Переменные окружения, передаваемые в контейнер. Это полезно для настройки подключения к базе данных и Redis.
        - name: DB_HOST  # Название переменной окружения для хоста базы данных.
          value: "postgres"  # Значение переменной - имя сервиса или хоста PostgreSQL.
        - name: DB_PORT  # Название переменной окружения для порта базы данных.
          value: "5432"  # Значение переменной - порт, на котором работает PostgreSQL (по умолчанию это 5432).
        - name: REDIS_HOST  # Название переменной окружения для хоста Redis.
          value: "redis"  # Значение переменной - имя сервиса или хоста Redis.
        - name: REDIS_PORT  # Название переменной окружения для порта Redis.
          value: "5370"  # Значение переменной - порт, на котором работает Redis (указан 5370, т.к. так в Docker Compose).
        - name: SECRET_KEY  # Название переменной окружения для секретного ключа приложения.
          valueFrom:
            secretKeyRef:  # Указывает, что значение переменной будет взято из Kubernetes Secret.
              name: app-secrets  # Имя секрета, где хранится `SECRET_KEY`. Этот секрет должен быть заранее создан в кластере.
              key: SECRET_KEY  # Ключ внутри секрета, где хранится значение для SECRET_KEY.
